### PR TITLE
Adding Vagrant configuration to support testing. 

### PR DESCRIPTION
**Pull request by whitingjr**
This commit will add a number of things needed to complete the integration and testing of Hyperfoil.

### CODE REVIEW

**Comment by whitingjr** [comment]
I've had to force push this branch. As the history had diverged from the original branch. The tip now is consistent again.

**Comment by eguzki** [comment]
It's ok to merge PR's instead of rebasing. Rebasing was meant for something else.

**Comment by whitingjr** [comment]
It does matter when other devs are using a forked branch. The history is very easy to diverge and a headache to ensure no mistakes are made.

**Comment by eguzki** [comment]
When more than one developer is working on the same base branch, i.e. `hyperfoil`, rebasing the base branch is **wrong**. That is the golden rule of rebasing. You have rebased a branch from which I started working. Now the base commits from which I started committing are gone.

**Pull request closed without merging**
